{ ... }:
let custom = {
    font = "JetBrainsMono Nerd Font";
    font_size = "14px";
    font_weight = "bold";
  };
in 
{
  programs.waybar.style = ''

    @import url("colors-waybar.css"); /* Dynamically generated by pywal */
    
    * {
        padding: 0;
        margin: 0;
        font-family: ${custom.font};
        font-size: ${custom.font_size};
        font-weight: ${custom.font_weight};
    }

    window#waybar {
        background-color: rgba(0, 0, 0, 0);
    }

    .modules-left {
        background-color: @color0;
        border-radius: 24px;
        padding-right: 8px;
        padding-left: 15px;
    }

    .modules-center {
        background-color: @color0;
        border-radius: 24px;
        padding-right: 10px;
        padding-left: 10px;
    }

    .modules-right {
        background-color: @color0;
        border-radius: 24px;
        padding-right: 15px;
        padding-left: 15px;
    }

    #custom-icon {
        font-size: 24px;
        color: @color4; 
        padding-right: 10px;
        margin-right: 5px;
    }

    #cpu,
    #memory,
    #temperature {
        font-size: 14px;
        background: @color0;
        margin-top: 5px;
        margin-bottom: 5px;
    }

    #cpu {
        color: #8ec07c;
        padding: 0px 10px 0px 12px;
        border-radius: 5px 0px 0px 5px;
    }

    #memory {
        color: #000000;
        padding: 0px 10px 0px 0px;
    }

    #temperature {
        color: #000000;
        padding: 0px 12px 0px 0px;
        border-radius: 0px 5px 5px 0px;
    }

    #window {
        margin-right: 10px;
        margin-left: 10px;
        color: #000000;
    }

    #workspaces button:nth-child(1) label {
        color: @color4;
        margin: 0px 8px;
    }

    #workspaces button:nth-child(2) label {
        color: @color5;
        margin: 0px 8px;
    }

    #workspaces button:nth-child(3) label {
        color: @color6;
        margin: 0px 8px;
    }

    #workspaces button:nth-child(4) label {
        color: @color7;
        margin: 0px 8px;
    }

    #workspaces button:nth-child(5) label {
        color: @color8;
        margin: 0px 8px;
    }

    #workspaces button:nth-child(6) label {
        color: @color8;
        margin: 0px 8px;
    }

    #battery {
        color: @color8;
        margin: 0px 10px 0px 0px;
    }

    #pulseaudio,
    #backlight {
        font-size: 14px;
        background: @color0;
        margin-top: 5px;
        margin-bottom: 5px;
        color: @color4;
        padding: 0px 10px 0px 10px;
        border-radius: 5px 0px 0px 5px;
    }

    #pulseaudio {
        color: @color5;
        padding: 0px 10px 0px 0px;
        border-radius: 0px 5px 5px 0px;
    }

    #custom-right-arr {
        color: @color4;
    }

    #network {
        color: @color4;
        margin-right: 10px;
    }

    #custom-dot {
        color: @color5;
        padding-left: 10px;
        padding-right: 10px;
    }

    #custom-dot-alt {
        color: #a5adcb;
        padding-left: 10px;
        padding-right: 10px;
    }

    #clock {
        padding-left: 10px;
        color: @color4;
        background-color: @color0;
        padding-right: 10px;
        margin-top: 5px;
        margin-bottom: 5px;
        border-radius: 5px;
    }
  '';
}
